### ISSUE TITLE
ventana de login

### ISSUE THREAD

**Issue by guillermohf** [PaisPosible/OpenPolitics#10]
Se desaparecen los campos de autentificacion

**Comment by alejandromorrison** [comment]
Hay que cambiarle la estetica

**Comment by alejandromorrison** [comment]
-[ ]El campo de contraseña no se borra cuando el usuario lo selecciona.
-[ ]Con el Enter no se da automaticamente al conectar y se verifica la informacion.
-[ ]Aun no se autentifica el login con el servidor y los usuarios que hay dentro de el.
-[ ]Autentificar la informacion con las bases de datos.
-[ ]que cuando se presione la tecla ESC, el programa se cierre automaticamente.
-[ ]Hacer que la ventana principal aparezca en el centro de la pantalla y que no sea resizable.

**Comment by alejandromorrison** [comment]
Dejamos esta parte, para cuando el gui este terminado. solo seria una condicion.

-[ ]Aun no se autentifica el login con el servidor y los usuarios que hay dentro de el.
-[ ]Autentificar la informacion con las bases de datos.
