### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by alejandromorrison** [PaisPosible/OpenPolitics#3]
If you could help guys in develop a readme, for anyone who wants to help in the development of the app,
This app is only for politics.

**Comment by saslamp** [comment]
Lets talk. I would love to do that. How's it going to be

**Comment by alejandromorrison** [comment]
Hi @saslamp Its a honour for us to have you on the team, if you can help with the README im not  an expert developing it, ut mainly the software gives us the oportunity to check the individual withing a range or a keyword in a country specified. and it let us to access throught our social media accounts. and that data will be downloaded to a postgresql database, for the storage of the data scraped.

**Comment by saslamp** [comment]
@alejandromorrison Great! So have you started working on the app?

**Comment by alejandromorrison** [comment]
Yes we just started. Do you want to join to slack? Right now we are setting up where to run it all. And we need a server for the tensorflow.
